export const datafilm = [
  {
    maPhim: 10530,
    tenPhim: "Kẻ Độc Hành",
    biDanh: "ke-doc-hanh",
    trailer: "https://youtu.be/_iyC2aUCxY0",
    hinhAnh: "http://movie0706.cybersoft.edu.vn/hinhanh/ke-doc-hanh_gp09.jpg",
    moTa: "Bộ phim sẽ được phát sóng dự kiến vào tháng 10/2022 Với 08 tập phim theo dạng web series, cùng sự góp mặt với hơn 30 nghệ sỹ, diễn viên… Với chi phí đầu tư lớn và được phát sóng trên nền tảng VOD. Ai Chết Giơ Tay (new season) với tên gọi Kẻ Độc Hành. Đây là dự án tâm huyết của Lập đã được chuẩn bị hơn 1 năm, đã được bấm máy vào tháng 05/2021 tại Long Xuyên AG (quê nhà của Lập) và sẽ được hậu kỳ hơn 1 năm.",
    maNhom: "GP09",
    ngayKhoiChieu: "2024-11-23T00:00:00",
    danhGia: 10,
  },
  {
    maPhim: 10531,
    tenPhim: "Nhà Bà Nữ",
    biDanh: "nha-ba-nu",
    trailer: "https://www.youtube.com/watch?v=1anBxcsV5b8",
    hinhAnh: "http://movie0706.cybersoft.edu.vn/hinhanh/nha-ba-nu_gp09.jpg",
    moTa: 'Ông Thái là một cảnh sát về hưu nhưng không chịu an phận thủ thường, hàng ngày vẫn đi tìm bắt tội phạm vặt trong xóm cho đỡ nhớ nghề. Một ngày kia, Hoàng - tên trùm ma túy mới ra tù bỗng dưng chuyển đến xóm ông và mở một văn phòng bất động sản. Nghi ngờ đây là nơi làm ăn phi pháp, ông Thái quyết định âm thầm điều tra. Ông mua lại tiệm cơm tấm đối diện trụ sở của Hoàng để làm nơi theo dõi, đồng thời thu nạp Thu - Phú - Vinh - Mèo, đám thanh niên “bất hảo” trong xóm về quán hỗ trợ buôn bán để rảnh tay "phá án". Trớ trêu thay, tiệm cơm bất ngờ nổi tiếng và ăn nên làm ra, khiến cho "chuyên án đặc biệt" của ông đứng trước nguy cơ đổ bể.',
    maNhom: "GP09",
    ngayKhoiChieu: "2022-05-28T00:00:00",
    danhGia: 10,
  },
  {
    maPhim: 10532,
    tenPhim: "Tăng tốc phía em",
    biDanh: "tang-toc-phia-em",
    trailer: "https://www.youtube.com/watch?v=h261_whvLPM",
    hinhAnh:
      "http://movie0706.cybersoft.edu.vn/hinhanh/tang-toc-phia-em_gp09.jpg",
    moTa: "Kao (Nat Kitcharit) là một nhà vô địch thế giới môn xếp ly tốc độ (Speed Stack). Tuy thành công và nổi tiếng nhưng Kao lại chỉ như một đứa trẻ to xác suốt ngày chỉ ăn, ngủ và tập luyện. Mọi vấn đề xung quanh anh đều một tay Jay (Yaya) bạn gái anh quán xuyến. Đến một ngày khi Jay quyết định chia tay thì Kao như bị mất tất cả. Anh phải bắt đầu học những kỹ năng sống cơ bản để có thể tự sống một mình và chăm sóc bản thân. Song song đó những đối thủ mới cũng xuất hiện và đe dọa đến vị trí quán quân của Kao.",
    maNhom: "GP09",
    ngayKhoiChieu: "2022-05-11T00:00:00",
    danhGia: 10,
  },
  {
    maPhim: 10533,
    tenPhim: "Phim cực kì hay",
    biDanh: "phim-cuc-ki-hay",
    trailer: "https://youtu.be/3xccmeAsy8g",
    hinhAnh:
      "http://movie0706.cybersoft.edu.vn/hinhanh/aaaaaaaaaaaaaaa_gp09.jpg",
    moTa: "Phim hay, nên đừng đổi mô tả nữa",
    maNhom: "GP09",
    ngayKhoiChieu: "2022-08-26T19:12:55.477",
    danhGia: 10,
  },
  {
    maPhim: 10606,
    tenPhim: "Nghề siêu dễ",
    biDanh: "nghe-sieu-de",
    trailer: "https://www.youtube.com/watch?v=ZOgNsZpLwvs",
    hinhAnh: "http://movie0706.cybersoft.edu.vn/hinhanh/aaaaaaaaaaa_gp09.jpg",
    moTa: "https://www.youtube.com/watch?v=ZOgNsZpLwvshttps://www.youtube.com/watch?v=ZOgNsZpLwvshttps://www.youtube.com/watch?v=ZOgNsZpLwvshttps://www.youtube.com/watch?v=ZOgNsZpLwvs",
    maNhom: "GP09",
    ngayKhoiChieu: "2022-05-15T00:00:00",
    danhGia: 10,
  },
  {
    maPhim: 10614,
    tenPhim: "RỪNG SĂN NGƯỜI",
    biDanh: "rung-san-nguoi",
    trailer: "https://www.youtube.com/watch?v=BRXHdMcU_co",
    hinhAnh:
      "http://movie0706.cybersoft.edu.vn/hinhanh/rung-san-nguoi_gp09.jpg",
    moTa: "Một biệt đội được phái vào rừng sâu để tìm tài liệu tuyệt mật và những người đồng đội mất tích. Nhưng mọi thứ không đơn giản như thế, họ đã tiến vào một vùng đất chất, nơi quỷ dữ thống trị và điều khiển mọi thứ. Đặc biệt, phim có sự góp mặt của Mickey Rourke, phản diện chính từ Iron Man 2.",
    maNhom: "GP09",
    ngayKhoiChieu: "2022-05-17T00:00:00",
    danhGia: 10,
  },
  {
    maPhim: 10647,
    tenPhim: "Black Adam",
    biDanh: "black-adam",
    trailer: "https://www.youtube.com/watch?v=N73oTiIIJe0",
    hinhAnh: "http://movie0706.cybersoft.edu.vn/hinhanh/black-adam_gp09.jpeg",
    moTa: "Mặc dù kế hoạch là Black Adam sẽ xuất hiện trong Shazam 2, thế nhưng nhà sản xuất quyết định cho nhân vật này ra một phần phim riêng. Black Adam là một pháp sư Ai Cập cổ đại được chọn làm người kế thừa sức mạnh Shazam tuy nhien hắn dần dần bị tha hoá về đạo đức và sự lạm dụng sức mạnh của mình. Chính vì vậy hắn đã bị phong ấn suốt mấy ngàn năm qua.",
    maNhom: "GP09",
    ngayKhoiChieu: "2023-04-29T00:00:00",
    danhGia: 10,
  },
  {
    maPhim: 10649,
    tenPhim: "Captain Marvel 2",
    biDanh: "captain-marvel-2",
    trailer: "https://www.youtube.com/watch?v=M3tBP1MyMB0",
    hinhAnh:
      "http://movie0706.cybersoft.edu.vn/hinhanh/captain-marvel-2_gp09.jpeg",
    moTa: "Diễn ra trong bối cảnh hiện đại sau những năm 1990 vintage của bộ phim gốc, Captain Marvel 2 sẽ tiếp nối sau sự kiện Avenger: Endgame với kịch bản được viết bởi Megan McDonnel (một trong những nhà biên kịch WandaVision). Chúng ta có thể tin rằng Carol Danvers sẽ được cách tân phù hợp với gam màu MCU hiện tại trong Captain Marvel 2.",
    maNhom: "GP09",
    ngayKhoiChieu: "2022-05-26T00:00:00",
    danhGia: 10,
  },
  {
    maPhim: 10765,
    tenPhim: "iron man 4",
    biDanh: "iron-man-4",
    trailer: "https://www.youtube.com/embed/SwwlFvOwkhA",
    hinhAnh: "http://movie0706.cybersoft.edu.vn/hinhanh/iron-man-4_gp09.jpg",
    moTa: "mota ironman",
    maNhom: "GP09",
    ngayKhoiChieu: "2022-07-01T00:00:00",
    danhGia: 10,
  },
  {
    maPhim: 10766,
    tenPhim: "Thor 5",
    biDanh: "thor-5",
    trailer: "https://www.youtube.com/embed/TyfBgQKsEXs",
    hinhAnh: "http://movie0706.cybersoft.edu.vn/hinhanh/thor-5_gp09.jpg",
    moTa: "than sam 5 hihihihihihiih hiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii\nhiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
    maNhom: "GP09",
    ngayKhoiChieu: "2022-07-03T00:00:00",
    danhGia: 10,
  },
  {
    maPhim: 10786,
    tenPhim: "test11",
    biDanh: "test11",
    trailer: "https://www.youtube.com/watch?v=M3tBP1MyMB0",
    hinhAnh: "http://movie0706.cybersoft.edu.vn/hinhanh/test11_gp09.png",
    moTa: "Test",
    maNhom: "GP09",
    ngayKhoiChieu: "2023-11-22T00:00:00",
    danhGia: 10,
  },
  {
    maPhim: 10840,
    tenPhim: "Detective Pikachu",
    biDanh: "detective-pikachu",
    trailer: "https://www.youtube.com/embed/1roy4o4tqQM",
    hinhAnh:
      "http://movie0706.cybersoft.edu.vn/hinhanh/detective-pikachu_gp09.jpg",
    moTa: "Good Pokemon: Detective Pikachu xoay quay hành trình truy tìm manh mối phá án về cái chết của Harry Goodman – thám tử mẫn cán ở thành phố Ryme của Tim Goodman và người bạn đồng hành siêu đáng yêu Pikachu. Là người duy nhất nghe được giọng nói thực của của Pikachu thay vì tiếng “Pika Pika” quen thuộc, Tim và Pikachu nhanh chóng trở thành bạn thân và cùng dấn thân vào cuộc điều tra những vụ mất tích bí ẩn trong thành phố. Trong hành trình phá án, cặp đôi “oan gia” này đã gây ra những tình huống trái ngang nhưng tràn đầy tiếng cười.",
    maNhom: "GP09",
    ngayKhoiChieu: "2022-11-07T00:00:00",
    danhGia: 9,
  },
  {
    maPhim: 10949,
    tenPhim: "evfweagwagÁDASDASDAS",
    biDanh: "evfweagwagadasdasdas",
    trailer: "https://www.youtube.com/watch?v=AghIqOvlxRQ",
    hinhAnh:
      "http://movie0706.cybersoft.edu.vn/hinhanh/evfweagwagadasdasdas_gp09.jpg",
    moTa: "aaa...",
    maNhom: "GP09",
    ngayKhoiChieu: "2024-10-26T00:00:00",
    danhGia: 10,
  },
  {
    maPhim: 10952,
    tenPhim: "TẤM VÉ ĐẾN THIÊN ĐƯỜNG",
    biDanh: "tam-ve-den-thien-duong",
    trailer: "https://www.youtube.com/watch?v=pyYq_iGzetM",
    hinhAnh:
      "http://movie0706.cybersoft.edu.vn/hinhanh/tam-ve-den-thien-duong_gp09.jpg",
    moTa: 'Hai diễn viên kỳ cựu của Hollywood - George Clooney và Julia Roberts sẽ tái hợp trên màn ảnh rộng trong vai đôi vợ chồng đã li hôn, nhưng lại cùng chung sứ mệnh ngăn cản cuộc kết hôn của đứa con gái yêu. Bởi họ sợ rằng con gái đang mắc phải sai lầm tương tự điều mà họ đã từng trải qua. Ticket to Paradise là một bộ phim hài lãng mạn về sự ngọt ngào bất ngờ của "cơ hội thứ hai”.',
    maNhom: "GP09",
    ngayKhoiChieu: "2022-10-14T00:00:00",
    danhGia: 10,
  },
  {
    maPhim: 10953,
    tenPhim: "TẤM VÉ ĐẾN THIÊN ĐƯỜN",
    biDanh: "tam-ve-den-thien-duon",
    trailer: "https://www.youtube.com/watch?v=pyYq_iGzetM",
    hinhAnh:
      "http://movie0706.cybersoft.edu.vn/hinhanh/tam-ve-den-thien-duon_gp09.jpg",
    moTa: 'Hai diễn viên kỳ cựu của Hollywood - George Clooney và Julia Roberts sẽ tái hợp trên màn ảnh rộng trong vai đôi vợ chồng đã li hôn, nhưng lại cùng chung sứ mệnh ngăn cản cuộc kết hôn của đứa con gái yêu. Bởi họ sợ rằng con gái đang mắc phải sai lầm tương tự điều mà họ đã từng trải qua. Ticket to Paradise là một bộ phim hài lãng mạn về sự ngọt ngào bất ngờ của "cơ hội thứ hai”.\r\n',
    maNhom: "GP09",
    ngayKhoiChieu: "2022-10-14T00:00:00",
    danhGia: 10,
  },
  {
    maPhim: 10984,
    tenPhim: "Aquaman 1",
    biDanh: "aquaman-1",
    trailer: "https://www.youtube.com/embed/YmHijIQrOiY",
    hinhAnh: "http://movie0706.cybersoft.edu.vn/hinhanh/aquaman-1_gp09.jpg",
    moTa: "Aquaman and the Lost Kingdom is an upcoming American superhero film based on the DC Comics character Aquaman. Produced by DC Films, The Safran Company, and Atomic Monster Productions, and set for distribution by Warner Bros. Pictures, it is intended to be the sequel to Aquaman (2018) and the thirteenth film in the DC Extended Universe (DCEU). The film is directed by James Wan from a screenplay written by David Leslie Johnson-McGoldrick, and stars Jason Momoa as Arthur Curry / Aquaman alongside Amber Heard, Willem Dafoe, Patrick Wilson, Dolph Lundgren, Yahya Abdul-Mateen II, Temuera Morrison, and Nicole Kidman.\r\n\r\nMomoa pitched a story for an Aquaman sequel during production of the first film. Wan did not want to rush a sequel but agreed in January 2019 to oversee development. Johnson-McGoldrick signed to write the screenplay a month later, and Wan was confirmed to be directing in August 2020. He said the film would expand on Aquaman's worldbuilding, and announced the sequel's title in June 2021. Filming began at the end of the month and concluded in January 2022, taking place in the United Kingdom, Hawaii, and Los Angeles.\r\n",
    maNhom: "GP09",
    ngayKhoiChieu: "2022-11-07T00:00:00",
    danhGia: 10,
  },
  {
    maPhim: 10985,
    tenPhim: "CÔ GÁI TỪ QUÁ KHỨ",
    biDanh: "co-gai-tu-qua-khu",
    trailer: "https://www.youtube.com/watch?v=WsBV9s1SqpM",
    hinhAnh:
      "http://movie0706.cybersoft.edu.vn/hinhanh/co-gai-tu-qua-khu_gp09.png",
    moTa: "Đang tất bật chuẩn bị cho đám cưới triệu đô cùng chàng Jack điển trai, đại mỹ nhân showbiz Ms. Q/Hoàng Quyên (Ninh Dương Lan Ngọc) bất ngờ mất tích một cách bí ẩn ngay sau khi gặp lại Quỳnh Yên (Kaity Nguyễn), một người bạn đã mất liên lạc từ 15 năm trước. Ngay lập tức, các rắc rối liên tục ập đến, kéo theo những bí mật đen tối của cả hai dần bị lột trần. Ai là kẻ thủ ác? Ai mới là nạn nhân? P/S: Bất kể cô ta có nói gì thì cũng nên nhớ: Đừng tin lời cô ta nói!",
    maNhom: "GP09",
    ngayKhoiChieu: "2022-10-24T00:00:00",
    danhGia: 10,
  },
  {
    maPhim: 10986,
    tenPhim: "black Adam",
    biDanh: "black-adam",
    trailer: "https://www.youtube.com/watch?v=uAop-vMrggI",
    hinhAnh: "http://movie0706.cybersoft.edu.vn/hinhanh/black-adam_gp09.jpg",
    moTa: "Dwayne Johnson sẽ góp mặt trong tác phẩm hành động - phiêu lưu mới của New Line Cinema “Black Adam”. Đây là bộ phim đầu tiên trên màn ảnh rộng khai thác câu chuyện của siêu anh hùng DC này, dưới sự sáng tạo của đạo diễn Jaume Collet-Serra (“Jungle Cruise”). \r\n\r\nGần 5.000 năm sau khi bị cầm tù với quyền năng tối thượng từ những vị thần cổ đại, Black Adam (Dwayne Johnson) sẽ được giải phóng khỏi nấm mồ chết chóc của mình, mang tới thế giới hiện đại một kiểu nhận thức về công lý hoàn toàn mới. \r\n\r\nBên cạnh Johnson, phim quy tụ dàn sao Aldis Hodge (“City on a Hill,” “One Night in Miami”) trong vai Hawkman, Noah Centineo (“To All the Boys I’ve Loved Before”) trong vai Atom Smasher, Sarah Shahi (“Sex/Life”, “Rush Hour 3”) trong vai Adrianna, Marwan Kenzari (“Murder on the Orient Express”, “The Mummy”) trong vai Ishmael, Quintessa Swindell (“Voyagers”, “Trinkets”) trong vai Cyclone, Bodhi Sabongui (“A Million Little Things”) trong vai Amon, và Pierce Brosnan (“Mamma Mia!” và loạt phim James Bond) trong vai Dr. Fate.\r\n\r\nCollet-Serra đạo diễn dựa trên kịch bản do Adam Sztykiel và Rory Haines & Sohrab Noshirvani chấp bút, với cốt truyện sáng tạo bởi Adam Sztykiel và Rory Haines & Sohrab Noshirvani, dựa trên nhân vật thuộc vũ trụ DC Black Adam sáng tạo bởi Bill Parker cùng C.C. Beck. Đội ngũ sản xuất phim bao gồm Beau Flynn, Dwayne Johnson, Hiram Garcia và Dany Garcia, cùng với Richard Brener, Walter Hamada, Dave Neustadter, Chris Pan, Eric McLeod, Geoff Johns và Scott Sheldon.\r\n\r\n“Black Adam” dự kiến sẽ công phá phòng vé  từ ngày 21.10.2022 với định dạng 2D và IMAX. Phim được phân phối toàn cầu bởi hàng Warner Bros. Pictures.",
    maNhom: "GP09",
    ngayKhoiChieu: "2022-10-25T00:00:00",
    danhGia: 10,
  },
  {
    maPhim: 10987,
    tenPhim: "Fantastic Beast",
    biDanh: "fantastic-beast",
    trailer: "https://www.youtube.com/embed/Y9dr2zw-TXQ",
    hinhAnh:
      "http://movie0706.cybersoft.edu.vn/hinhanh/fantastic-beast_gp09.jpg",
    moTa: "Warner Bros. Pictures’ “Fantastic Beasts: The Secrets of Dumbledore” is the newest adventure in the Wizarding World™ created by J.K. Rowling.\r\n\r\nProfessor Albus Dumbledore (Jude Law) knows the powerful Dark wizard Gellert Grindelwald (Mads Mikkelsen) is moving to seize control of the wizarding world. Unable to stop him alone, he entrusts Magizoologist Newt Scamander (Eddie Redmayne) to lead an intrepid team of wizards, witches and one brave Muggle baker on a dangerous mission, where they encounter old and new beasts and clash with Grindelwald’s growing legion of followers. But with the stakes so high, how long can Dumbledore remain on the sidelines?\r\n\r\nThe film features an ensemble cast led by Oscar winner Eddie Redmayne (“The Theory of Everything”), two-time Oscar nominee Jude Law (“Cold Mountain,” “The Talented Mr. Ripley”), Ezra Miller, Dan Fogler, Alison Sudol, Callum Turner, Jessica Williams, Katherine Waterston, and Mads Mikkelsen.\r\n\r\n“Fantastic Beasts: The Secrets of Dumbledore” was directed by David Yates, from a screenplay by J.K. Rowling & Steve Kloves, based upon a screenplay by J.K. Rowling. The film was produced by David Heyman, J.K. Rowling, Steve Kloves, Lionel Wigram and Tim Lewis. Neil Blair, Danny Cohen, Josh Berger, Courtenay Valenti and Michael Sharp served as executive producers.\r\n\r\nThe film’s behind-the-scenes creative team included director of photography George Richmond (“Rocketman,” “Kingsman: The Golden Circle”), three-time Oscar-winning production designer Stuart Craig (“The English Patient,” “Dangerous Liaisons,” “Gandhi,” the “Harry Potter” and “Fantastic Beasts” films) and production designer Neil Lamont (“Solo: A Star Wars Story,” “Rogue One: A Star Wars Story”), four-time Oscar-winning costume designer Colleen Atwood (“Chicago,” “Memoirs of a Geisha,” “Alice in Wonderland,” “Fantastic Beasts\r\nand Where to Find Them”), and Yates’ longtime editor Mark Day (“Fantastic Beasts: The Crimes of Grindelwald,” the last four “Harry Potter” films). The music is by nine-time Oscar nominee James Newton Howard (“News of the World,” “Fantastic Beasts: The Crimes of Grindelwald,” “Defiance,” “Michael Clayton,” “The Hunger Games” films).\r\n\r\nWarner Bros. Pictures presents a Heyday Films Production, a David Yates film, “Fantastic Beasts: The Secrets of Dumbledore,” in theaters internationally beginning 7 April 2022 and in North America on April 15, 2022. The film will be distributed worldwide in select theatres and IMAX by Warner Bros. Pictures.",
    maNhom: "GP09",
    ngayKhoiChieu: "2022-11-07T00:00:00",
    danhGia: 10,
  },
  {
    maPhim: 10988,
    tenPhim: "Phim chữ B",
    biDanh: "phim-chu-b",
    trailer: "https://www.youtube.com/watch?v=pyYq_iGzetM",
    hinhAnh: "http://movie0706.cybersoft.edu.vn/hinhanh/phim-chu-b_gp09.jpg",
    moTa: "B",
    maNhom: "GP09",
    ngayKhoiChieu: "2022-09-29T00:00:00",
    danhGia: 10,
  },
  {
    maPhim: 10989,
    tenPhim: "BỖNG DƯNG TRÚNG SỐ",
    biDanh: "bong-dung-trung-so",
    trailer: "https://www.youtube.com/embed/D3KbO3QF-lg",
    hinhAnh:
      "http://movie0706.cybersoft.edu.vn/hinhanh/bong-dung-trung-so_gp09.png",
    moTa: "Người lính Hàn Quốc Chun Woo (Ko Kyoung-pyo) vô tình nhặt được tờ vé số trúng độc đắc trị giá lên đến gần 6 triệu đô! Nhưng chưa kịp vui mừng bao lâu, tờ vé số ấy không may bị cuốn bay sang bên kia biên giới và rơi vào tay anh lính Triều Tiên Yong Ho (Lee Yi-kyung). Chun Woo cần tờ vé số để đổi tiền, trong khi Yong Ho dù nắm giữ tờ vé quan trọng lại không thể đặt chân đến Hàn Quốc. Câu chuyện ngày càng trở nên rắc rối và hài hước khi có thêm những người đồng đội của hai anh chàng biết được sự việc và nhất quyết tham gia vào cuộc đàm phán chia tiền.",
    maNhom: "GP09",
    ngayKhoiChieu: "2022-11-07T23:03:34.007",
    danhGia: 10,
  },
  {
    maPhim: 11393,
    tenPhim: "strinxg",
    biDanh: "strinxg",
    trailer: "https://youtu.be/Pcvh3MVB98A?si=evXny5CKK8VybCva",
    hinhAnh: "http://movie0706.cybersoft.edu.vn/hinhanh/strinxg_gp09.jpg",
    moTa: "string",
    maNhom: "GP09",
    ngayKhoiChieu: "2021-02-03T00:00:00",
    danhGia: 10,
  },
  {
    maPhim: 11413,
    tenPhim: "John Cena WWE",
    biDanh: "john-cena-wwe",
    trailer: "https://www.youtube.com/watch?v=hvSzRkz1SWE",
    hinhAnh: "http://movie0706.cybersoft.edu.vn/hinhanh/john-cena-wwe_gp09.jpg",
    moTa: "Good film... 222!",
    maNhom: "GP09",
    ngayKhoiChieu: "2023-11-02T00:00:00",
    danhGia: 9,
  },
  {
    maPhim: 11530,
    tenPhim: "Ngoi Den",
    biDanh: "ngoi-den",
    trailer: "https://www.youtube.com/watch?v=8okbTEu7Op8",
    hinhAnh: "http://movie0706.cybersoft.edu.vn/hinhanh/ngoi-den_gp09.jpg",
    moTa: "sd",
    maNhom: "GP09",
    ngayKhoiChieu: "2024-06-16T00:00:00",
    danhGia: 9,
  },
];
export const datafilm2 = [
  {
    heThongRapChieu: [
      {
        cumRapChieu: [
          {
            lichChieuPhim: [
              {
                maLichChieu: "43324",
                maRap: "451",
                tenRap: "Rạp 1",
                ngayChieuGioChieu: "2020-10-02T02:10:00",
                giaVe: 150000,
                thoiLuong: 120,
              },
            ],
            maCumRap: "bhd-star-cineplex-3-2",
            tenCumRap: "BHD Star Cineplex - 3/2",
            hinhAnh: null,
          },
        ],
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
        logo: "http://movie0706.cybersoft.edu.vn/hinhanh/bhd-star-cineplex.png",
      },
      {
        cumRapChieu: [
          {
            lichChieuPhim: [
              {
                maLichChieu: "43488",
                maRap: "701",
                tenRap: "Rạp 1",
                ngayChieuGioChieu: "2021-07-07T12:00:00",
                giaVe: 75000,
                thoiLuong: 120,
              },
            ],
            maCumRap: "cgv-vincom-thu-duc",
            tenCumRap: "CGV - Vincom Thủ Đức",
            hinhAnh: null,
          },
        ],
        maHeThongRap: "CGV",
        tenHeThongRap: "cgv",
        logo: "http://movie0706.cybersoft.edu.vn/hinhanh/cgv.png",
      },
      {
        cumRapChieu: [
          {
            lichChieuPhim: [
              {
                maLichChieu: "43401",
                maRap: "731",
                tenRap: "Rạp 1",
                ngayChieuGioChieu: "2021-06-05T23:04:00",
                giaVe: 85000,
                thoiLuong: 120,
              },
              {
                maLichChieu: "43402",
                maRap: "733",
                tenRap: "Rạp 3",
                ngayChieuGioChieu: "2021-06-10T13:40:00",
                giaVe: 85000,
                thoiLuong: 120,
              },
            ],
            maCumRap: "cns-quoc-thanh",
            tenCumRap: "CNS - Quốc Thanh",
            hinhAnh: null,
          },
          {
            lichChieuPhim: [
              {
                maLichChieu: "43403",
                maRap: "721",
                tenRap: "Rạp 1",
                ngayChieuGioChieu: "2021-06-18T13:40:00",
                giaVe: 100000,
                thoiLuong: 120,
              },
            ],
            maCumRap: "cns-hai-ba-trung",
            tenCumRap: "CNS - Hai Bà Trưng",
            hinhAnh: null,
          },
        ],
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
        logo: "http://movie0706.cybersoft.edu.vn/hinhanh/cinestar.png",
      },
      {
        cumRapChieu: [
          {
            lichChieuPhim: [
              {
                maLichChieu: "43981",
                maRap: "744",
                tenRap: "Rạp 4",
                ngayChieuGioChieu: "2021-07-09T15:47:00",
                giaVe: 100000,
                thoiLuong: 120,
              },
            ],
            maCumRap: "glx-huynh-tan-phat",
            tenCumRap: "GLX - Huỳnh Tấn Phát",
            hinhAnh: null,
          },
        ],
        maHeThongRap: "Galaxy",
        tenHeThongRap: "Galaxy Cinema",
        logo: "http://movie0706.cybersoft.edu.vn/hinhanh/galaxy-cinema.png",
      },
    ],
    maPhim: 6820,
    tenPhim: "Avengers: End Game",
    biDanh: "avengers-end-game",
    trailer: "https://www.youtube.com/embed/egK0y4b-YhE",
    hinhAnh:
      "http://movie0706.cybersoft.edu.vn/hinhanh/avengers-end-game_gp09.jpg",
    moTa: "Sau sự kiện Thanos làm cho một nửa vũ trụ tan biến và khiến cho biệt đội Avengers thảm bại, những siêu anh hùng sống sót phải tham gia trận chiến cuối cùng trong Avengers: Endgame",
    maNhom: "GP09",
    ngayKhoiChieu: "2021-07-07T00:00:00",
    danhGia: 10,
  },
  {
    heThongRapChieu: [
      {
        cumRapChieu: [
          {
            lichChieuPhim: [
              {
                maLichChieu: "43452",
                maRap: "451",
                tenRap: "Rạp 1",
                ngayChieuGioChieu: "2021-07-07T21:25:00",
                giaVe: 75000,
                thoiLuong: 120,
              },
            ],
            maCumRap: "bhd-star-cineplex-3-2",
            tenCumRap: "BHD Star Cineplex - 3/2",
            hinhAnh: null,
          },
        ],
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
        logo: "http://movie0706.cybersoft.edu.vn/hinhanh/bhd-star-cineplex.png",
      },
    ],
    maPhim: 7048,
    tenPhim: "Liên Minh Công Lý",
    biDanh: "lien-minh-cong-ly",
    trailer: "https://www.youtube.com/embed/-EIGzsQILt4",
    hinhAnh:
      "http://movie0706.cybersoft.edu.vn/hinhanh/lien-minh-cong-ly_gp09.jpg",
    moTa: "Để cái chết của Siêu Nhân không phí hoài, Người Dơi cùng Nữ thần Chiến binh lên kế hoạch chiêu mộ một nhóm những người cường hóa để bảo vệ thế giới khỏi một mối đe dọa khủng khiếp sắp tới.",
    maNhom: "GP09",
    ngayKhoiChieu: "2021-07-08T00:00:00",
    danhGia: 9,
  },
  {
    heThongRapChieu: [
      {
        cumRapChieu: [
          {
            lichChieuPhim: [
              {
                maLichChieu: "44879",
                maRap: "451",
                tenRap: "Rạp 1",
                ngayChieuGioChieu: "2021-09-30T09:38:48",
                giaVe: 75000,
                thoiLuong: 120,
              },
              {
                maLichChieu: "44911",
                maRap: "451",
                tenRap: "Rạp 1",
                ngayChieuGioChieu: "2021-09-29T01:08:53",
                giaVe: 75000,
                thoiLuong: 120,
              },
            ],
            maCumRap: "bhd-star-cineplex-3-2",
            tenCumRap: "BHD Star Cineplex - 3/2",
            hinhAnh: null,
          },
          {
            lichChieuPhim: [
              {
                maLichChieu: "44912",
                maRap: "464",
                tenRap: "Rạp 4",
                ngayChieuGioChieu: "2021-09-29T01:09:10",
                giaVe: 75000,
                thoiLuong: 120,
              },
            ],
            maCumRap: "bhd-star-cineplex-bitexco",
            tenCumRap: "BHD Star Cineplex - Bitexco",
            hinhAnh: null,
          },
          {
            lichChieuPhim: [
              {
                maLichChieu: "44913",
                maRap: "506",
                tenRap: "Rạp 6",
                ngayChieuGioChieu: "2021-09-29T01:09:26",
                giaVe: 75000,
                thoiLuong: 120,
              },
            ],
            maCumRap: "bhd-star-cineplex-vincom-thao-dien",
            tenCumRap: "BHD Star Cineplex - Vincom Thảo Điền",
            hinhAnh: null,
          },
        ],
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
        logo: "http://movie0706.cybersoft.edu.vn/hinhanh/bhd-star-cineplex.png",
      },
      {
        cumRapChieu: [
          {
            lichChieuPhim: [
              {
                maLichChieu: "44880",
                maRap: "511",
                tenRap: "Rạp 1",
                ngayChieuGioChieu: "2021-09-30T09:39:03",
                giaVe: 75000,
                thoiLuong: 120,
              },
            ],
            maCumRap: "cgv-aeon-binh-tan",
            tenCumRap: "CGV - Aeon Bình Tân",
            hinhAnh: null,
          },
        ],
        maHeThongRap: "CGV",
        tenHeThongRap: "cgv",
        logo: "http://movie0706.cybersoft.edu.vn/hinhanh/cgv.png",
      },
      {
        cumRapChieu: [
          {
            lichChieuPhim: [
              {
                maLichChieu: "44881",
                maRap: "721",
                tenRap: "Rạp 1",
                ngayChieuGioChieu: "2021-09-30T09:39:39",
                giaVe: 75000,
                thoiLuong: 120,
              },
            ],
            maCumRap: "cns-hai-ba-trung",
            tenCumRap: "CNS - Hai Bà Trưng",
            hinhAnh: null,
          },
        ],
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
        logo: "http://movie0706.cybersoft.edu.vn/hinhanh/cinestar.png",
      },
      {
        cumRapChieu: [
          {
            lichChieuPhim: [
              {
                maLichChieu: "44551",
                maRap: "814",
                tenRap: "Rạp 4",
                ngayChieuGioChieu: "2021-09-09T05:00:00",
                giaVe: 75000,
                thoiLuong: 120,
              },
            ],
            maCumRap: "glx-trung-chanh",
            tenCumRap: "GLX - Trung Chánh",
            hinhAnh: null,
          },
          {
            lichChieuPhim: [
              {
                maLichChieu: "44842",
                maRap: "777",
                tenRap: "Rạp 7",
                ngayChieuGioChieu: "2021-09-27T11:21:59",
                giaVe: 80000,
                thoiLuong: 120,
              },
            ],
            maCumRap: "glx-nguyen-van-qua",
            tenCumRap: "GLX - Nguyễn Văn Quá",
            hinhAnh: null,
          },
        ],
        maHeThongRap: "Galaxy",
        tenHeThongRap: "Galaxy Cinema",
        logo: "http://movie0706.cybersoft.edu.vn/hinhanh/galaxy-cinema.png",
      },
      {
        cumRapChieu: [
          {
            lichChieuPhim: [
              {
                maLichChieu: "44882",
                maRap: "834",
                tenRap: "Rạp 4",
                ngayChieuGioChieu: "2021-09-30T12:00:45",
                giaVe: 75000,
                thoiLuong: 120,
              },
            ],
            maCumRap: "lotte-cong-hoa",
            tenCumRap: "Lotte - Cộng Hòa",
            hinhAnh: null,
          },
        ],
        maHeThongRap: "LotteCinima",
        tenHeThongRap: "Lotte Cinema",
        logo: "http://movie0706.cybersoft.edu.vn/hinhanh/lotte-cinema.png",
      },
      {
        cumRapChieu: [
          {
            lichChieuPhim: [
              {
                maLichChieu: "44883",
                maRap: "907",
                tenRap: "Rạp 7",
                ngayChieuGioChieu: "2021-09-30T12:00:50",
                giaVe: 75000,
                thoiLuong: 120,
              },
            ],
            maCumRap: "megags-cao-thang",
            tenCumRap: "MegaGS - Cao Thắng",
            hinhAnh: null,
          },
        ],
        maHeThongRap: "MegaGS",
        tenHeThongRap: "MegaGS",
        logo: "http://movie0706.cybersoft.edu.vn/hinhanh/megags.png",
      },
    ],
    maPhim: 8367,
    tenPhim: "Peaky blinders",
    biDanh: "peaky-blinders",
    trailer: "https://www.youtube.com/embed/oVzVdvGIC7U",
    hinhAnh:
      "http://movie0706.cybersoft.edu.vn/hinhanh/peaky-blinders_gp09.jpg",
    moTa: "Bóng ma Anh Quốc là một bộ phim chính kịch truyền hình tội phạm của Anh, được sản xuất vào năm 2013 bởi đạo diễn Steven Knight. Loạt phim lấy bối cảnh tại thành phố Birmingham, kể về sự khai thác của Gia đình tội phạm Shelby trong hậu quả trực tiếp của Thế chiến thứ nhất",
    maNhom: "GP09",
    ngayKhoiChieu: "2021-09-29T00:00:00",
    danhGia: 10,
  },
  {
    heThongRapChieu: [
      {
        cumRapChieu: [
          {
            lichChieuPhim: [
              {
                maLichChieu: "44602",
                maRap: "451",
                tenRap: "Rạp 1",
                ngayChieuGioChieu: "2021-09-14T12:00:09",
                giaVe: 75000,
                thoiLuong: 120,
              },
            ],
            maCumRap: "bhd-star-cineplex-3-2",
            tenCumRap: "BHD Star Cineplex - 3/2",
            hinhAnh: null,
          },
          {
            lichChieuPhim: [
              {
                maLichChieu: "44908",
                maRap: "486",
                tenRap: "Rạp 6",
                ngayChieuGioChieu: "2021-09-29T01:08:04",
                giaVe: 75000,
                thoiLuong: 120,
              },
            ],
            maCumRap: "bhd-star-cineplex-vincom-le-van-viet",
            tenCumRap: "BHD Star Cineplex - Vincom Lê Văn Việt",
            hinhAnh: null,
          },
          {
            lichChieuPhim: [
              {
                maLichChieu: "44909",
                maRap: "495",
                tenRap: "Rạp 5",
                ngayChieuGioChieu: "2021-09-29T01:08:19",
                giaVe: 75000,
                thoiLuong: 120,
              },
            ],
            maCumRap: "bhd-star-cineplex-vincom-quang-trung",
            tenCumRap: "BHD Star Cineplex - Vincom Quang Trung",
            hinhAnh: null,
          },
          {
            lichChieuPhim: [
              {
                maLichChieu: "44910",
                maRap: "506",
                tenRap: "Rạp 6",
                ngayChieuGioChieu: "2021-09-29T01:08:35",
                giaVe: 75000,
                thoiLuong: 120,
              },
            ],
            maCumRap: "bhd-star-cineplex-vincom-thao-dien",
            tenCumRap: "BHD Star Cineplex - Vincom Thảo Điền",
            hinhAnh: null,
          },
        ],
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
        logo: "http://movie0706.cybersoft.edu.vn/hinhanh/bhd-star-cineplex.png",
      },
      {
        cumRapChieu: [
          {
            lichChieuPhim: [
              {
                maLichChieu: "44867",
                maRap: "777",
                tenRap: "Rạp 7",
                ngayChieuGioChieu: "2021-09-30T01:56:47",
                giaVe: 75000,
                thoiLuong: 120,
              },
            ],
            maCumRap: "glx-nguyen-van-qua",
            tenCumRap: "GLX - Nguyễn Văn Quá",
            hinhAnh: null,
          },
        ],
        maHeThongRap: "Galaxy",
        tenHeThongRap: "Galaxy Cinema",
        logo: "http://movie0706.cybersoft.edu.vn/hinhanh/galaxy-cinema.png",
      },
    ],
    maPhim: 8368,
    tenPhim: "Sons of Anarchy",
    biDanh: "sons-of-anarchy",
    trailer: "https://www.youtube.com/embed/-Nv9YrZr3wE",
    hinhAnh:
      "http://movie0706.cybersoft.edu.vn/hinhanh/sons-of-anarchy_gp09.jpg",
    moTa: "Sons of Anarchy là một bộ phim truyền hình tội phạm hành động của Mỹ do Kurt Sutter tạo ra, được phát sóng từ năm 2008 đến năm 2014. Phim kể về cuộc sống của một câu lạc bộ mô tô ngoài vòng pháp luật hoạt động ở Charming, một thị trấn hư cấu ở Thung lũng Trung tâm của California",
    maNhom: "GP09",
    ngayKhoiChieu: "2021-09-29T00:00:00",
    danhGia: 10,
  },
  {
    heThongRapChieu: [
      {
        cumRapChieu: [
          {
            lichChieuPhim: [
              {
                maLichChieu: "44899",
                maRap: "451",
                tenRap: "Rạp 1",
                ngayChieuGioChieu: "2021-09-29T12:57:10",
                giaVe: 75000,
                thoiLuong: 120,
              },
            ],
            maCumRap: "bhd-star-cineplex-3-2",
            tenCumRap: "BHD Star Cineplex - 3/2",
            hinhAnh: null,
          },
          {
            lichChieuPhim: [
              {
                maLichChieu: "44900",
                maRap: "462",
                tenRap: "Rạp 2",
                ngayChieuGioChieu: "2021-09-29T12:57:27",
                giaVe: 75000,
                thoiLuong: 120,
              },
            ],
            maCumRap: "bhd-star-cineplex-bitexco",
            tenCumRap: "BHD Star Cineplex - Bitexco",
            hinhAnh: null,
          },
          {
            lichChieuPhim: [
              {
                maLichChieu: "44901",
                maRap: "474",
                tenRap: "Rạp 4",
                ngayChieuGioChieu: "2021-09-29T12:57:42",
                giaVe: 75000,
                thoiLuong: 120,
              },
            ],
            maCumRap: "bhd-star-cineplex-pham-hung",
            tenCumRap: "BHD Star Cineplex - Phạm Hùng",
            hinhAnh: null,
          },
        ],
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
        logo: "http://movie0706.cybersoft.edu.vn/hinhanh/bhd-star-cineplex.png",
      },
      {
        cumRapChieu: [
          {
            lichChieuPhim: [
              {
                maLichChieu: "44862",
                maRap: "773",
                tenRap: "Rạp 3",
                ngayChieuGioChieu: "2021-09-30T01:54:32",
                giaVe: 75000,
                thoiLuong: 120,
              },
            ],
            maCumRap: "glx-nguyen-van-qua",
            tenCumRap: "GLX - Nguyễn Văn Quá",
            hinhAnh: null,
          },
        ],
        maHeThongRap: "Galaxy",
        tenHeThongRap: "Galaxy Cinema",
        logo: "http://movie0706.cybersoft.edu.vn/hinhanh/galaxy-cinema.png",
      },
    ],
    maPhim: 8399,
    tenPhim: "Hannibal Lector",
    biDanh: "hannibal-lector",
    trailer: "https://www.youtube.com/embed/Es3B24z8fdA",
    hinhAnh:
      "http://movie0706.cybersoft.edu.vn/hinhanh/hannibal-lector_gp09.jpg",
    moTa: "Hannibal là một bộ phim truyền hình nhiều tập thuộc thể loại kinh dị viễn tưởng, điều tra hiện trường vụ án của Mỹ, sản xuất năm 2012 và được phát triển bởi Bryan Fuller cho kênh truyền hình NBC",
    maNhom: "GP09",
    ngayKhoiChieu: "2021-09-29T00:00:00",
    danhGia: 10,
  },
  {
    heThongRapChieu: [
      {
        cumRapChieu: [
          {
            lichChieuPhim: [
              {
                maLichChieu: "44884",
                maRap: "452",
                tenRap: "Rạp 2",
                ngayChieuGioChieu: "2021-09-29T09:41:46",
                giaVe: 75000,
                thoiLuong: 120,
              },
            ],
            maCumRap: "bhd-star-cineplex-3-2",
            tenCumRap: "BHD Star Cineplex - 3/2",
            hinhAnh: null,
          },
        ],
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
        logo: "http://movie0706.cybersoft.edu.vn/hinhanh/bhd-star-cineplex.png",
      },
      {
        cumRapChieu: [
          {
            lichChieuPhim: [
              {
                maLichChieu: "44885",
                maRap: "514",
                tenRap: "Rạp 4",
                ngayChieuGioChieu: "2021-09-29T09:42:06",
                giaVe: 75000,
                thoiLuong: 120,
              },
            ],
            maCumRap: "cgv-aeon-binh-tan",
            tenCumRap: "CGV - Aeon Bình Tân",
            hinhAnh: null,
          },
        ],
        maHeThongRap: "CGV",
        tenHeThongRap: "cgv",
        logo: "http://movie0706.cybersoft.edu.vn/hinhanh/cgv.png",
      },
      {
        cumRapChieu: [
          {
            lichChieuPhim: [
              {
                maLichChieu: "44886",
                maRap: "733",
                tenRap: "Rạp 3",
                ngayChieuGioChieu: "2021-09-29T09:42:20",
                giaVe: 75000,
                thoiLuong: 120,
              },
            ],
            maCumRap: "cns-quoc-thanh",
            tenCumRap: "CNS - Quốc Thanh",
            hinhAnh: null,
          },
        ],
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
        logo: "http://movie0706.cybersoft.edu.vn/hinhanh/cinestar.png",
      },
      {
        cumRapChieu: [
          {
            lichChieuPhim: [
              {
                maLichChieu: "44860",
                maRap: "771",
                tenRap: "Rạp 1",
                ngayChieuGioChieu: "2021-09-30T01:53:33",
                giaVe: 80000,
                thoiLuong: 120,
              },
            ],
            maCumRap: "glx-nguyen-van-qua",
            tenCumRap: "GLX - Nguyễn Văn Quá",
            hinhAnh: null,
          },
          {
            lichChieuPhim: [
              {
                maLichChieu: "44887",
                maRap: "742",
                tenRap: "Rạp 2",
                ngayChieuGioChieu: "2021-09-30T12:00:25",
                giaVe: 75000,
                thoiLuong: 120,
              },
            ],
            maCumRap: "glx-huynh-tan-phat",
            tenCumRap: "GLX - Huỳnh Tấn Phát",
            hinhAnh: null,
          },
        ],
        maHeThongRap: "Galaxy",
        tenHeThongRap: "Galaxy Cinema",
        logo: "http://movie0706.cybersoft.edu.vn/hinhanh/galaxy-cinema.png",
      },
      {
        cumRapChieu: [
          {
            lichChieuPhim: [
              {
                maLichChieu: "44888",
                maRap: "834",
                tenRap: "Rạp 4",
                ngayChieuGioChieu: "2021-09-30T12:00:32",
                giaVe: 75000,
                thoiLuong: 120,
              },
            ],
            maCumRap: "lotte-cong-hoa",
            tenCumRap: "Lotte - Cộng Hòa",
            hinhAnh: null,
          },
        ],
        maHeThongRap: "LotteCinima",
        tenHeThongRap: "Lotte Cinema",
        logo: "http://movie0706.cybersoft.edu.vn/hinhanh/lotte-cinema.png",
      },
      {
        cumRapChieu: [
          {
            lichChieuPhim: [
              {
                maLichChieu: "44889",
                maRap: "903",
                tenRap: "Rạp 3",
                ngayChieuGioChieu: "2021-09-30T12:00:34",
                giaVe: 75000,
                thoiLuong: 120,
              },
            ],
            maCumRap: "megags-cao-thang",
            tenCumRap: "MegaGS - Cao Thắng",
            hinhAnh: null,
          },
        ],
        maHeThongRap: "MegaGS",
        tenHeThongRap: "MegaGS",
        logo: "http://movie0706.cybersoft.edu.vn/hinhanh/megags.png",
      },
    ],
    maPhim: 8487,
    tenPhim: "The Gangster, The Cop, The Devil",
    biDanh: "the-gangster-the-cop-the-devil",
    trailer: "https://www.youtube.com/embed/_96SVqqFltA",
    hinhAnh:
      "http://movie0706.cybersoft.edu.vn/hinhanh/the-gangster-the-cop-the-devil_gp09.jpg",
    moTa: "The Gangster, the Cop, the Devil là một bộ phim kinh dị hành động tội phạm của Hàn Quốc năm 2019 của đạo diễn Lee Won-tae. Phim có sự tham gia của Ma Dong-seok, Kim Mu-yeol và Kim Sung-kyu. Cốt truyện dựa trên một câu chuyện có thật",
    maNhom: "GP09",
    ngayKhoiChieu: "2021-09-30T00:00:00",
    danhGia: 10,
  },
  {
    heThongRapChieu: [
      {
        cumRapChieu: [
          {
            lichChieuPhim: [
              {
                maLichChieu: "44610",
                maRap: "451",
                tenRap: "Rạp 1",
                ngayChieuGioChieu: "2021-11-21T10:40:00",
                giaVe: 90000,
                thoiLuong: 120,
              },
              {
                maLichChieu: "44611",
                maRap: "451",
                tenRap: "Rạp 1",
                ngayChieuGioChieu: "2021-11-22T11:40:00",
                giaVe: 90000,
                thoiLuong: 120,
              },
            ],
            maCumRap: "bhd-star-cineplex-3-2",
            tenCumRap: "BHD Star Cineplex - 3/2",
            hinhAnh: null,
          },
        ],
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
        logo: "http://movie0706.cybersoft.edu.vn/hinhanh/bhd-star-cineplex.png",
      },
      {
        cumRapChieu: [
          {
            lichChieuPhim: [
              {
                maLichChieu: "44612",
                maRap: "511",
                tenRap: "Rạp 1",
                ngayChieuGioChieu: "2021-11-23T12:40:00",
                giaVe: 90000,
                thoiLuong: 120,
              },
              {
                maLichChieu: "44613",
                maRap: "511",
                tenRap: "Rạp 1",
                ngayChieuGioChieu: "2021-11-24T13:40:00",
                giaVe: 90000,
                thoiLuong: 120,
              },
            ],
            maCumRap: "cgv-aeon-binh-tan",
            tenCumRap: "CGV - Aeon Bình Tân",
            hinhAnh: null,
          },
        ],
        maHeThongRap: "CGV",
        tenHeThongRap: "cgv",
        logo: "http://movie0706.cybersoft.edu.vn/hinhanh/cgv.png",
      },
      {
        cumRapChieu: [
          {
            lichChieuPhim: [
              {
                maLichChieu: "44614",
                maRap: "721",
                tenRap: "Rạp 1",
                ngayChieuGioChieu: "2021-11-25T14:40:00",
                giaVe: 90000,
                thoiLuong: 120,
              },
              {
                maLichChieu: "44615",
                maRap: "721",
                tenRap: "Rạp 1",
                ngayChieuGioChieu: "2021-11-26T14:40:00",
                giaVe: 90000,
                thoiLuong: 120,
              },
            ],
            maCumRap: "cns-hai-ba-trung",
            tenCumRap: "CNS - Hai Bà Trưng",
            hinhAnh: null,
          },
        ],
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
        logo: "http://movie0706.cybersoft.edu.vn/hinhanh/cinestar.png",
      },
      {
        cumRapChieu: [
          {
            lichChieuPhim: [
              {
                maLichChieu: "44616",
                maRap: "741",
                tenRap: "Rạp 1",
                ngayChieuGioChieu: "2021-11-27T15:40:00",
                giaVe: 90000,
                thoiLuong: 120,
              },
              {
                maLichChieu: "44617",
                maRap: "741",
                tenRap: "Rạp 1",
                ngayChieuGioChieu: "2021-11-28T16:40:00",
                giaVe: 90000,
                thoiLuong: 120,
              },
            ],
            maCumRap: "glx-huynh-tan-phat",
            tenCumRap: "GLX - Huỳnh Tấn Phát",
            hinhAnh: null,
          },
        ],
        maHeThongRap: "Galaxy",
        tenHeThongRap: "Galaxy Cinema",
        logo: "http://movie0706.cybersoft.edu.vn/hinhanh/galaxy-cinema.png",
      },
      {
        cumRapChieu: [
          {
            lichChieuPhim: [
              {
                maLichChieu: "44618",
                maRap: "821",
                tenRap: "Rạp 1",
                ngayChieuGioChieu: "2021-11-29T17:40:00",
                giaVe: 90000,
                thoiLuong: 120,
              },
              {
                maLichChieu: "44619",
                maRap: "821",
                tenRap: "Rạp 1",
                ngayChieuGioChieu: "2021-11-30T18:40:00",
                giaVe: 90000,
                thoiLuong: 120,
              },
            ],
            maCumRap: "lotte-cantavil",
            tenCumRap: "Lotte - Cantavil",
            hinhAnh: null,
          },
        ],
        maHeThongRap: "LotteCinima",
        tenHeThongRap: "Lotte Cinema",
        logo: "http://movie0706.cybersoft.edu.vn/hinhanh/lotte-cinema.png",
      },
      {
        cumRapChieu: [
          {
            lichChieuPhim: [
              {
                maLichChieu: "44620",
                maRap: "901",
                tenRap: "Rạp 1",
                ngayChieuGioChieu: "2021-11-01T19:40:00",
                giaVe: 90000,
                thoiLuong: 120,
              },
              {
                maLichChieu: "44621",
                maRap: "901",
                tenRap: "Rạp 1",
                ngayChieuGioChieu: "2021-11-02T16:40:00",
                giaVe: 90000,
                thoiLuong: 120,
              },
            ],
            maCumRap: "megags-cao-thang",
            tenCumRap: "MegaGS - Cao Thắng",
            hinhAnh: null,
          },
        ],
        maHeThongRap: "MegaGS",
        tenHeThongRap: "MegaGS",
        logo: "http://movie0706.cybersoft.edu.vn/hinhanh/megags.png",
      },
    ],
    maPhim: 8527,
    tenPhim: "Tru Tiên",
    biDanh: "tru-tien",
    trailer: "https://www.youtube.com/embed/SefkmMcA-0E",
    hinhAnh: "http://movie0706.cybersoft.edu.vn/hinhanh/tru-tien_gp09.jpg",
    moTa: "Tru Tiên 2 - Thanh Vân Chí 2 (2016) là bộ phim truyền hình cổ trang tiên hiệp cải biên từ tiểu thuyết Tru Tiên của Tiêu Đỉnh. Bộ phim kể về thiếu niên Trương Tiểu Phàm ở thôn Thảo Miêu gia nhập Thanh Vân Môn, cùng với con gái của Quỷ Vương là Bích Dao, người bạn tốt là Lâm Kinh Vũ, Lục Tuyết Kỳ, Tăng Thư Thư cùng những thiếu niên khác giúp đỡ người lương thiện, trừ yêu diệt ác, cuối cùng làm thất bại âm mưu làm Thần Thú sống lại, điên đảo thanh vân của Quỷ Vương",
    maNhom: "GP09",
    ngayKhoiChieu: "2022-01-12T00:00:00",
    danhGia: 10,
  },
  {
    heThongRapChieu: [
      {
        cumRapChieu: [
          {
            lichChieuPhim: [
              {
                maLichChieu: "44683",
                maRap: "451",
                tenRap: "Rạp 1",
                ngayChieuGioChieu: "2021-11-14T17:50:00",
                giaVe: 90000,
                thoiLuong: 120,
              },
              {
                maLichChieu: "44684",
                maRap: "451",
                tenRap: "Rạp 1",
                ngayChieuGioChieu: "2021-11-15T17:50:00",
                giaVe: 90000,
                thoiLuong: 120,
              },
            ],
            maCumRap: "bhd-star-cineplex-3-2",
            tenCumRap: "BHD Star Cineplex - 3/2",
            hinhAnh: null,
          },
        ],
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
        logo: "http://movie0706.cybersoft.edu.vn/hinhanh/bhd-star-cineplex.png",
      },
      {
        cumRapChieu: [
          {
            lichChieuPhim: [
              {
                maLichChieu: "44685",
                maRap: "511",
                tenRap: "Rạp 1",
                ngayChieuGioChieu: "2021-11-16T17:50:00",
                giaVe: 90000,
                thoiLuong: 120,
              },
              {
                maLichChieu: "44686",
                maRap: "511",
                tenRap: "Rạp 1",
                ngayChieuGioChieu: "2021-11-17T17:50:00",
                giaVe: 90000,
                thoiLuong: 120,
              },
            ],
            maCumRap: "cgv-aeon-binh-tan",
            tenCumRap: "CGV - Aeon Bình Tân",
            hinhAnh: null,
          },
        ],
        maHeThongRap: "CGV",
        tenHeThongRap: "cgv",
        logo: "http://movie0706.cybersoft.edu.vn/hinhanh/cgv.png",
      },
      {
        cumRapChieu: [
          {
            lichChieuPhim: [
              {
                maLichChieu: "44687",
                maRap: "721",
                tenRap: "Rạp 1",
                ngayChieuGioChieu: "2021-11-18T17:50:00",
                giaVe: 90000,
                thoiLuong: 120,
              },
              {
                maLichChieu: "44688",
                maRap: "721",
                tenRap: "Rạp 1",
                ngayChieuGioChieu: "2021-11-19T17:50:00",
                giaVe: 90000,
                thoiLuong: 120,
              },
            ],
            maCumRap: "cns-hai-ba-trung",
            tenCumRap: "CNS - Hai Bà Trưng",
            hinhAnh: null,
          },
        ],
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
        logo: "http://movie0706.cybersoft.edu.vn/hinhanh/cinestar.png",
      },
      {
        cumRapChieu: [
          {
            lichChieuPhim: [
              {
                maLichChieu: "44689",
                maRap: "741",
                tenRap: "Rạp 1",
                ngayChieuGioChieu: "2021-11-20T17:50:00",
                giaVe: 90000,
                thoiLuong: 120,
              },
              {
                maLichChieu: "44690",
                maRap: "741",
                tenRap: "Rạp 1",
                ngayChieuGioChieu: "2021-11-21T17:50:00",
                giaVe: 90000,
                thoiLuong: 120,
              },
            ],
            maCumRap: "glx-huynh-tan-phat",
            tenCumRap: "GLX - Huỳnh Tấn Phát",
            hinhAnh: null,
          },
        ],
        maHeThongRap: "Galaxy",
        tenHeThongRap: "Galaxy Cinema",
        logo: "http://movie0706.cybersoft.edu.vn/hinhanh/galaxy-cinema.png",
      },
      {
        cumRapChieu: [
          {
            lichChieuPhim: [
              {
                maLichChieu: "44691",
                maRap: "821",
                tenRap: "Rạp 1",
                ngayChieuGioChieu: "2021-11-22T17:50:00",
                giaVe: 90000,
                thoiLuong: 120,
              },
              {
                maLichChieu: "44692",
                maRap: "821",
                tenRap: "Rạp 1",
                ngayChieuGioChieu: "2021-11-23T17:50:00",
                giaVe: 90000,
                thoiLuong: 120,
              },
            ],
            maCumRap: "lotte-cantavil",
            tenCumRap: "Lotte - Cantavil",
            hinhAnh: null,
          },
        ],
        maHeThongRap: "LotteCinima",
        tenHeThongRap: "Lotte Cinema",
        logo: "http://movie0706.cybersoft.edu.vn/hinhanh/lotte-cinema.png",
      },
      {
        cumRapChieu: [
          {
            lichChieuPhim: [
              {
                maLichChieu: "44693",
                maRap: "901",
                tenRap: "Rạp 1",
                ngayChieuGioChieu: "2021-11-24T17:50:00",
                giaVe: 90000,
                thoiLuong: 120,
              },
              {
                maLichChieu: "44694",
                maRap: "901",
                tenRap: "Rạp 1",
                ngayChieuGioChieu: "2021-11-25T17:50:00",
                giaVe: 90000,
                thoiLuong: 120,
              },
              {
                maLichChieu: "44695",
                maRap: "901",
                tenRap: "Rạp 1",
                ngayChieuGioChieu: "2021-11-26T17:50:00",
                giaVe: 90000,
                thoiLuong: 120,
              },
              {
                maLichChieu: "44696",
                maRap: "901",
                tenRap: "Rạp 1",
                ngayChieuGioChieu: "2021-11-27T17:50:00",
                giaVe: 90000,
                thoiLuong: 120,
              },
              {
                maLichChieu: "44697",
                maRap: "901",
                tenRap: "Rạp 1",
                ngayChieuGioChieu: "2021-11-28T17:50:00",
                giaVe: 90000,
                thoiLuong: 120,
              },
            ],
            maCumRap: "megags-cao-thang",
            tenCumRap: "MegaGS - Cao Thắng",
            hinhAnh: null,
          },
        ],
        maHeThongRap: "MegaGS",
        tenHeThongRap: "MegaGS",
        logo: "http://movie0706.cybersoft.edu.vn/hinhanh/megags.png",
      },
    ],
    maPhim: 8533,
    tenPhim: "Doraemon: Nobita và Chiến Tranh Vũ Trụ",
    biDanh: "doraemon-nobita-va-chien-tranh-vu-tru",
    trailer: "https://www.youtube.com/embed/twtjj-tuwaY",
    hinhAnh:
      "http://movie0706.cybersoft.edu.vn/hinhanh/doraemon-nobita-va-chien-tranh-vu-tru_gp09.jpg",
    moTa: "Phim Doraemon: Nobita Và Chuyến Thám Hiểm Nam Cực Kachi Kochi xoay quanh câu chuyện về chuyến thám hiểm Nam Cực của Nobita cùng nhóm bạn trẻ lớp 3E. Để tránh cái nóng oi bức của mùa hè, Nobita và những người bạn đã tìm đến một tảng băng trôi lớn và tự xây cho mình một công viên bằng băng từ những bảo bối của Doraemon.",
    maNhom: "GP09",
    ngayKhoiChieu: "2021-09-16T13:55:13.917",
    danhGia: 10,
  },
  {
    heThongRapChieu: [
      {
        cumRapChieu: [
          {
            lichChieuPhim: [
              {
                maLichChieu: "44809",
                maRap: "451",
                tenRap: "Rạp 1",
                ngayChieuGioChieu: "2021-09-25T06:36:19",
                giaVe: 90000,
                thoiLuong: 120,
              },
              {
                maLichChieu: "44810",
                maRap: "451",
                tenRap: "Rạp 1",
                ngayChieuGioChieu: "2021-09-30T06:36:50",
                giaVe: 90000,
                thoiLuong: 120,
              },
            ],
            maCumRap: "bhd-star-cineplex-3-2",
            tenCumRap: "BHD Star Cineplex - 3/2",
            hinhAnh: null,
          },
        ],
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
        logo: "http://movie0706.cybersoft.edu.vn/hinhanh/bhd-star-cineplex.png",
      },
      {
        cumRapChieu: [
          {
            lichChieuPhim: [
              {
                maLichChieu: "44772",
                maRap: "512",
                tenRap: "Rạp 2",
                ngayChieuGioChieu: "2021-09-30T05:57:45",
                giaVe: 80000,
                thoiLuong: 120,
              },
              {
                maLichChieu: "44808",
                maRap: "511",
                tenRap: "Rạp 1",
                ngayChieuGioChieu: "2021-09-17T06:08:20",
                giaVe: 75000,
                thoiLuong: 120,
              },
            ],
            maCumRap: "cgv-aeon-binh-tan",
            tenCumRap: "CGV - Aeon Bình Tân",
            hinhAnh: null,
          },
        ],
        maHeThongRap: "CGV",
        tenHeThongRap: "cgv",
        logo: "http://movie0706.cybersoft.edu.vn/hinhanh/cgv.png",
      },
      {
        cumRapChieu: [
          {
            lichChieuPhim: [
              {
                maLichChieu: "44791",
                maRap: "901",
                tenRap: "Rạp 1",
                ngayChieuGioChieu: "2021-09-20T12:05:06",
                giaVe: 76000,
                thoiLuong: 120,
              },
            ],
            maCumRap: "megags-cao-thang",
            tenCumRap: "MegaGS - Cao Thắng",
            hinhAnh: null,
          },
        ],
        maHeThongRap: "MegaGS",
        tenHeThongRap: "MegaGS",
        logo: "http://movie0706.cybersoft.edu.vn/hinhanh/megags.png",
      },
    ],
    maPhim: 8645,
    tenPhim: "Bloodshot",
    biDanh: "bloodshot",
    trailer: "https://www.youtube.com/watch?v=TcMBFSGVi1c",
    hinhAnh: "http://movie0706.cybersoft.edu.vn/hinhanh/bloodshot_gp09.jpg",
    moTa: "Siêu anh hùng Bloodshot là bộ phim được định hình mở màn cho loạt phim lấy bối cảnh trong vũ trụ điện ảnh Valiant Comics. Nhân vật chính của phim là tài tử Vin Diesel, với đạo diễn  David SF Wilson kết hợp cùng kịch bản của Jeff Wadlow và Eric Heisserer. Phim xoay quanh câu chuyện của một thuỷ quân lục chiến đã bị giết trong lúc hành động, tuy nhiên anh đã được hồi sinh với siêu năng lực bởi một tổ chức ngầm muốn dùng anh như một vũ khí để loại trừ các đối thủ.",
    maNhom: "GP09",
    ngayKhoiChieu: "2021-09-15T00:00:00",
    danhGia: 10,
  },
  {
    heThongRapChieu: [
      {
        cumRapChieu: [
          {
            lichChieuPhim: [
              {
                maLichChieu: "44924",
                maRap: "451",
                tenRap: "Rạp 1",
                ngayChieuGioChieu: "2021-09-29T01:15:17",
                giaVe: 75000,
                thoiLuong: 120,
              },
            ],
            maCumRap: "bhd-star-cineplex-3-2",
            tenCumRap: "BHD Star Cineplex - 3/2",
            hinhAnh: null,
          },
          {
            lichChieuPhim: [
              {
                maLichChieu: "44925",
                maRap: "463",
                tenRap: "Rạp 3",
                ngayChieuGioChieu: "2021-09-29T01:15:33",
                giaVe: 75000,
                thoiLuong: 120,
              },
              {
                maLichChieu: "44926",
                maRap: "464",
                tenRap: "Rạp 4",
                ngayChieuGioChieu: "2021-09-29T01:15:51",
                giaVe: 75000,
                thoiLuong: 120,
              },
            ],
            maCumRap: "bhd-star-cineplex-bitexco",
            tenCumRap: "BHD Star Cineplex - Bitexco",
            hinhAnh: null,
          },
          {
            lichChieuPhim: [
              {
                maLichChieu: "44927",
                maRap: "475",
                tenRap: "Rạp 5",
                ngayChieuGioChieu: "2021-09-29T01:16:05",
                giaVe: 75000,
                thoiLuong: 120,
              },
            ],
            maCumRap: "bhd-star-cineplex-pham-hung",
            tenCumRap: "BHD Star Cineplex - Phạm Hùng",
            hinhAnh: null,
          },
        ],
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
        logo: "http://movie0706.cybersoft.edu.vn/hinhanh/bhd-star-cineplex.png",
      },
      {
        cumRapChieu: [
          {
            lichChieuPhim: [
              {
                maLichChieu: "44874",
                maRap: "777",
                tenRap: "Rạp 7",
                ngayChieuGioChieu: "2021-09-30T02:00:02",
                giaVe: 75000,
                thoiLuong: 120,
              },
            ],
            maCumRap: "glx-nguyen-van-qua",
            tenCumRap: "GLX - Nguyễn Văn Quá",
            hinhAnh: null,
          },
        ],
        maHeThongRap: "Galaxy",
        tenHeThongRap: "Galaxy Cinema",
        logo: "http://movie0706.cybersoft.edu.vn/hinhanh/galaxy-cinema.png",
      },
    ],
    maPhim: 8902,
    tenPhim: "Sherlock Holmes",
    biDanh: "sherlock-holmes",
    trailer: "https://www.youtube.com/embed/J7nJksXDBWc",
    hinhAnh:
      "http://movie0706.cybersoft.edu.vn/hinhanh/sherlock-holmes_gp09.jpg",
    moTa: "Sherlock Holmes 3: Mọi thứ chúng ta biết (từ trước đến nay) về Robert Downey, Jr. Threequel. Mặc dù cái chết của Tony Stark đang tàn phá đối với khán giả xem phim, nhưng điều đó đã làm nên điều kỳ diệu cho các nhượng quyền thương mại khác của Robert Downey, Jr. Anh ấy bắt đầu một loạt phim khởi động lại Dr.",
    maNhom: "GP09",
    ngayKhoiChieu: "2021-12-16T16:02:51.5",
    danhGia: 10,
  },
];
